abbs = {
    "stn": "Measuring station",
    "soc": "",
    "fracsec": "Timestamp, fraction of seconds",
    "vm1": "Voltage magnitude L1",
    "vm2": "Voltage magnitude L2",
    "vm3": "Voltage magnitude L3",
    "vm4": "Voltage magnitude L4",
    "im1": "Current magnitude L1",
    "im2": "Current magnitude L2",
    "im3": "Current magnitude L3",
    "im4": "Current magnitude L4",
    "vph1": "Voltage phase L1",
    "vph2": "Voltage phase L2",
    "vph3": "Voltage phase L3",
    "vph4": "Voltage phase L4",
    "iph1": "Current phase L1",
    "iph2": "Current phase L2",
    "iph3": "Current phase L3",
    "iph4": "Current phase L4",
    "f": "Frequency",
    "df": "RoCof",
    "vzsm": "Voltage zero sequence magnitude",
    "izsm": "Current zero sequence magnitude",
    "vzsph": "Voltage zero sequence phase",
    "izsph": "Current zero sequence phase",
}